name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: 'actions/checkout@v2'
 
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: '${{ secrets.GCP_INSTANCE }}'
          zone: '${{ secrets.GCP_INSTANCE_ZONE }}'
          ssh_private_key: '${{ secrets.SSH_KEY }}'
          user: '${{ secrets.GCP_USER }}'
          script: |
            cd ~/forum-api
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forum-api